### ISSUE TITLE
Error during use of GDML module within master GDML file

### ISSUE THREAD

**Issue by xanfus** [KeithSloan/GDML#113]
File: importGDML.py.
Call to _processPhysVolFile_ at line 1980 has 3 arguments, while function definition at line 2734 has 4.
```
17:24:01  Process PhysVols
17:24:01  pv <Element physvol at 0x7f04fa162440>
17:24:01  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/xanfus/.local/share/FreeCAD/Mod/GDML/./freecad/gdml/importGDML.py", line 96, in open
    processGDML(doc, True, filename, True, False)
  File "/home/xanfus/.local/share/FreeCAD/Mod/GDML/./freecad/gdml/importGDML.py", line 3093, in processGDML
    parseVolume(doc, volDict, part, world, phylvl, 3)
  File "/home/xanfus/.local/share/FreeCAD/Mod/GDML/./freecad/gdml/importGDML.py", line 2062, in parseVolume
    expandVolume(doc, volDict, parent, name, phylvl, displayMode)
  File "/home/xanfus/.local/share/FreeCAD/Mod/GDML/./freecad/gdml/importGDML.py", line 2426, in expandVolume
    processVol(doc, vol, volDict, parent, phylvl, displayMode)
  File "/home/xanfus/.local/share/FreeCAD/Mod/GDML/./freecad/gdml/importGDML.py", line 2353, in processVol
    part = parsePhysVol(
  File "/home/xanfus/.local/share/FreeCAD/Mod/GDML/./freecad/gdml/importGDML.py", line 1980, in parsePhysVol
    processPhysVolFile(doc, parent, fname)
<class 'TypeError'>: processPhysVolFile() missing 1 required positional argument: 'fname'
```

**Comment by KeithSloan** [comment]
Thank you for reporting.

Not sure how that bug crept in, line 1980 should have been processPhysVolFile(doc, volDict, parent, fname)

Main branch should now be fix.

Please reopen if you find otherwise.
